### ISSUE TITLE
Make gallery with default name values

### ISSUE THREAD

**Issue by ragreenburg** [haltakov/simple-photo-gallery#108]
I am basically writing this thing to make a gallery with this library at the push of a button but the issue I am having is that when the button is pressed it runs the `gallery-init` in the background but that requires a user input for name values. Is there then a way to run that and just have it automatically assign the default values without question? Not a bug really but I couldn't find an email address to send one out and I don't have a Twitter account so this was the only way to reach out. In short though, what I am looking to do is run a subprocess which runs `gallery-init`, `gallery-build` and then open the html with the click of a button but the issue seems to be that this won't work because `gallery-init` needs more inputs from the user.

**Comment by haltakov** [comment]
This is theoretically possible, but not easy to implement... Let me do a quick fix to add a parameter to do this.

**Comment by haltakov** [comment]
If you want to contact me per e-mail just use my <first name>.<last name>@gmail.com

**Comment by haltakov** [comment]
OK, the feature is now available in version 1.5.1. I documented the usage here: https://github.com/haltakov/simple-photo-gallery/blob/master/doc/Usage.md#skip-questions-on-the-console

Basically, you can just call it like this:
```
gallery-init --use-defaults
```

I will appreciate it if you drop me an e-mail with some more information on how you are using the gallery. It will be interesting to me to see because I have some ideas for version 2.0.0 :) Thank you!

(first name).(last name)@gmail.com
