### ISSUE TITLE
Add support for .png files

### ISSUE THREAD

**Issue by Zenahr** [haltakov/simple-photo-gallery#80]
png images are not recognized, thus the gallery is not built. Either implicit conversion should be applied (since jpegs are generally smaller than pngs) or they should just be added the same way jpegs are added to the gallery.

**Comment by haltakov** [comment]
I implemented support for PNG files. I think implicit conversion to JPG is not the correct way, because it will be converting from a lossless to a lossy compression. 

I can see some use-cases for this, like for example having a gallery with app/website screenshots. This features makes sense, so thanks for reporting.

**Comment by Zenahr** [comment]
At least this saves the user from explicitly converting all their images to jpg instead of just uploading them.

For image compression at build-time Gatsby is a pretty great inspiration:
https://www.gatsbyjs.org/packages/gatsby-image

**Comment by haltakov** [comment]
I agree this makes sense as an option. I created an issue for that: https://github.com/haltakov/simple-photo-gallery/issues/83
