### ISSUE TITLE
Link for each section 

### ISSUE THREAD

**Issue by tyeeman** [haltakov/simple-photo-gallery#95]
Is there a way to make each section linkable? If I want to send a friend to one specific section with a url can it be done?

**Comment by haltakov** [comment]
It is not implemented, but it is actually very easy to do. Give me an hour max... :)

**Comment by haltakov** [comment]
OK, I implemented this feature and released a new version (1.3.5): https://pypi.org/project/simple-photo-gallery/1.3.5/. You will now see a small link icon next to the title, when you move your mouse over it. When you click it it will take you to the section link. You can then just copy it and send it.

If you want to update your gallery without creating a new one you just need to replace the following two files:
- `templates/gallery_macros.jinja`
- `public/css/main.css`

You can update and  just create a new empty gallery somewhere and copy the two files over to your existing gallery.

Btw. since you are using the gallery regularly, you can contact me directly per e-mail at `<first name>.<last name>@gmail.com` or on Twitter `@haltakov`. It will be easier to communicate as over Github Issues :)

**Comment by tyeeman** [comment]
Works great, thanks!
